// <auto-generated />
namespace Demo2Mvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Adds_Language_Class : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adds_Language_Class));
        
        string IMigrationMetadata.Id
        {
            get { return "202003130624180_Adds_Language_Class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
