// <auto-generated />
namespace Demo2Mvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class RenameName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameName));
        
        string IMigrationMetadata.Id
        {
            get { return "202002240914533_RenameName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
