// <auto-generated />
namespace Demo2Mvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class adds_many_to_many_relations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adds_many_to_many_relations));
        
        string IMigrationMetadata.Id
        {
            get { return "202003130630391_adds_many_to_many_relations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
